### ISSUE TITLE
Request: Support for Ore Shrubs

### ISSUE THREAD

**Issue by esotericist** [MinecraftModDevelopmentMods/Bush-Master-Core#4]
I can see that you have support for the [Ore Berries](https://minecraft.curseforge.com/projects/oreberries) mod, but my server primarily makes use of the [Ore Shrubs](https://minecraft.curseforge.com/projects/ore-shrubs/) mod instead.

Would it be possible for you to support this as well?

**Comment by faceofcat** [comment]
it would... :)

I actually tried to... but in my creative world I couldn't place the shrubs down... so... I had no way of testing and gave up... or they were placed down but wouldn't grow... something like that...

I will try again when I get some time.

**Comment by faceofcat** [comment]
also... the Ore Berries dev actually PR-ed support into this... ;)... that would also be an awesome thing for more people to do.

**Comment by esotericist** [comment]
Ha, yeah.

In a perfect world, all modders would coordinate on all such things, but people have limited timeframes, which is why I'm always hesitant to ask for support like this... But I figured for a project whose stated purpose is this kind of cross compatibility, it wouldn't hurt to at least mention it.

Regarding getting ore shrubs to grow, they're a bit quirky. I don't know about the Ore Berries mod, but these are really picky about light level, and you have to use a custom fertilizer in order to force growth. They're also heavy on NBT, so I'm not actually clear if getting them in creative mode gets a valid version of the shrub.

Tell you what: I'm getting ready to do some mod testing tonight (including giving your Powered Thingies mod a test drive), so I'll see if I can't put together a /give command for you to get a known-valid ore shrub for your own testing.

Would that help?

**Comment by faceofcat** [comment]
sure thing... that would be awesome...

or... worst case scenario... I must find time and go hunt for these thingies in their natural habitat... caves I guess?... :)

**Comment by esotericist** [comment]
Hint: Make a [Lost Cities](https://minecraft.curseforge.com/projects/the-lost-cities) world, head into the subways. They're FILLED with the damn things.

Granted, they're mostly aluminum (presuming you have a mod with those) and sometime uranium (which strikes me as incredibly unsafe, and I've been considering adjusting THAT config setting), but hey. Awesome shrubs require you to go deeper than the subway. 😀

**Comment by esotericist** [comment]
I was mistaken: they don't actually use NBT. I guess the dev changed how they work at some point in the last several versions?

A simple `/give <name> oreshrubs:oreshrub_iron` will do the job. Place it in a dark space, and feed it fertilizer (`/give <name> oreshrubs:shrub_fertilizer` until it starts emitting berries.

Now, the actual BERRIES produced are NBT based in the form of:
`/give <name> oreshrubs:oreberries 1 0 {OreShrubVariant:{Name:"iron"}}`

This is just from casual in-game inspection. Source for the mod is available, but I'm not currently in the right mental space to stare at java.
